# Site
repository: Shobhit1/Shobhit1.github.io
# favicon: images/favicon.ico

# Personal info
name: Shobhit Agarwal
title: Software Engineer II
email: shobhit657@gmail.com
website: sagarwal.xyz

# Social links
twitter_username: shob2811
github_username: Shobhit1
linkedin_username: shobhit28
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile_shobhit.jpg
about_content: | # this will include new lines to allow paragraphs
    Hi, my name's Shobhit and I'm a software engineer at [Microsoft](https://github.com/microsoft) working on [Accessibility Insights](https://accessibilityinsights.io)
        I am most skilled in: <mark>Javascript</mark> and <mark>Analyzing Liverpool FC games</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
    Alongside my interests in networks and software engineering some of my other interests and hobbies are:
     - FIFA on XBOX
     - Hiking around PNW

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
    sass_dir: _sass
    style: compressed

plugins:
    - jekyll-seo-tag

theme: jekyll-theme-tactile
